export const REQUEST_MOVIES = 'REQUEST_MOVIES'
export const RECEIVE_MOVIES = 'RECEIVE_MOVIES'
export const REQUEST_MOVIE_DETAILS = 'REQUEST_MOVIE_DETAILS'
export const RECEIVE_MOVIE_DETAILS = 'RECEIVE_MOVIE_DETAILS'